// MEMBUAT VARIABEL YANG ISINYA PERINTAH SQL UNTUK MENAMPILKAN DATA
string query = "SELECT * FROM namaTabel;";

// MEMBUKA KONEKSI
KONEKSI_DATABASE.Open();

// MEMBUAT DATA ADAPTER DENGAN NAMA "da"
SqlDataAdapter da = new SqlDataAdapter(query, KONEKSI_DATABASE);

// MEMBUAT OBJEK DATASET DENGAN NAMA "ds"
DataSet ds = new DataSet();

// MENGISI DATASET DARI DATA ADAPTER
da.Fill(ds);

// MENGISI DATAGRIDVIEW DARI DATA SET
datagridview1.DataSource = ds.Tables[0];

// MENUTUP KONEKSI
KONEKSI_DATABASE.Close();
